# In recent versions of Dockerfile, EXPOSE doesn't have any operational
# impact anymore, it is just informative.
#
# In older versions of Docker, the EXPOSE keyword could be used for service
# discovery by linked containers, but (a) it still didn't have any operational
# impact -- the ports were available whether or not there was a matching EXPOSE
# -- and container "linking" has been deprecated for a quite some time.

services:
  mustore:
    image: ghashy/mustore:0.1
    expose:
      - "8000"
    secrets:
      - object-storage-key-id
      - object-storage-access-key
      - email-authorization-token
      - redis-password
      - postgres-password
      - localhost-recaptcha-secret-key
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: mustore
      APP_CONFIG_FILE: /app/config/local-compose.yaml
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-password
      REDIS_PASSWORD_FILE: /run/secrets/redis-password
      EMAIL_AUTHORIZATION_TOKEN_FILE: /run/secrets/email-authorization-token
      OBJECT_STORAGE_KEY_ID_FILE: /run/secrets/object-storage-key-id
      OBJECT_STORAGE_ACCESS_KEY_FILE: /run/secrets/object-storage-access-key
      RECAPTCHA_SECRET_KEY_FILE: /run/secrets/localhost-recaptcha-secret-key
      ENVIRONMENT: development
    networks:
      default:
      customnetwork:
        ipv4_address: 172.20.0.11
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      minio:
        condition: service_healthy
      email-mock:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health_check"]
      # The health check will first run interval seconds after the container is 
      # started, and then again interval seconds after each previous check 
      # completes.
      interval: 5s
      # If a single run of the check takes longer than timeout seconds then the 
      # check is considered to have failed.
      timeout: 5s
      # It takes retries consecutive failures of the health check for the 
      # container to be considered unhealthy.
      retries: 2
      # Start period provides initialization time for containers that need time 
      # to bootstrap. Probe failure during that period will not be counted 
      # towards the maximum number of retries. However, if a health check 
      # succeeds during the start period, the container is considered started 
      # and all consecutive failures will be counted towards the maximum number 
      # of retries.
      start_period: 3s

  email-mock:
    image: ghashy/email-mock:0.1
    expose:
      - "8001"
    networks:
      - default
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health_check"]
      interval: 5s
      timeout: 5s
      retries: 2
      start_period: 2s

  postgres:
    image: postgres:16.1-alpine3.18
    restart: always
    user: postgres
    secrets:
      - postgres-password
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=mustore
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-password
    expose:
      - "5432"
    networks:
      - default
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 2

  redis:
    image: redis:alpine
    secrets:
      - redis-password
    environment:
      REDIS_PASSWORD_FILE: /run/secrets/redis-password
    command: sh -c "redis-server --requirepass $(cat $$REDIS_PASSWORD_FILE)"
    volumes:
      - redis_volume:/data
    expose:
      - "6379"
    networks:
      - default
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "$(cat $$REDIS_PASSWORD_FILE)", "ping"]
      interval: 5s
      timeout: 5s
      retries: 2
      start_period: 2s

  minio:
    image: minio/minio
    secrets:
      - object-storage-key-id
      - object-storage-access-key
    command: server /data --console-address ":9001"
    volumes:
      - minio_volume:/data
    ports:
      - 9000:9000
      - 9001:9001
    networks:
      customnetwork:
        ipv4_address: 172.20.0.10
    environment:
      MINIO_DOMAIN: minio
      MINIO_SITE_REGION: ru-central1
      MINIO_ROOT_USER_FILE: /run/secrets/object-storage-key-id
      MINIO_ROOT_PASSWORD_FILE: /run/secrets/object-storage-access-key
    healthcheck:
      test: timeout 5s bash -c ':> /dev/tcp/127.0.0.1/9000' || exit 1
      interval: 5s
      timeout: 5s
      retries: 2
      start_period: 2s

  nginx:
    image: nginx:alpine
    restart: always
    volumes:
      - ./config/nginx-compose.conf:/etc/nginx/nginx.conf
    ports:
      - "10000:10000"
    networks:
      - default
    depends_on:
      mustore:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "service", "nginx", "status"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s

volumes:
  redis_volume:
  minio_volume:
  postgres_volume:

secrets:
  local-compose-config:
    file: secrets/local-compose.yaml
  postgres-password:
    file: secrets/postgres_password.txt
  redis-password:
    file: secrets/redis_password.txt
  email-authorization-token:
    file: secrets/email_client_authorization_token.txt
  object-storage-key-id:
    file: secrets/object_storage_key_id.txt
  object-storage-access-key:
    file: secrets/object_storage_access_key.txt
  localhost-recaptcha-secret-key:
    file: secrets/localhost_recaptcha_secret_key.txt

networks:
  customnetwork:
    ipam:
      config:
        - subnet: 172.20.0.0/16
  default: {}

