app_port: 8000
app_addr: "0.0.0.0"
app_base_url: "http://localhost:10000" # This is address of our nginx instance
email_delivery_service: smtp
database:
  host: "postgres"
  port: 5432
redis:
  host: "redis"
  port: 6379
  db_number: 0
email_client:
  base_url: "http://email-mock:8001"
  sender_email: "anymail@anydomain.com"
  timeout: 10000
object_storage: # We run object storage manually on pc
  endpoint_url: "http://192.168.31.150:3900" # This is addres of computer in home network, on which object storage is run
  region: "garage"
  bucket_name: "mustore-data"
recaptcha:
  endpoint_url: "https://www.google.com/recaptcha/api/siteverify"
payments:
  merchant_api_endpoint: "http://banksim:15100"
