app_port: 8000
app_addr: "127.0.0.1"
app_base_url: "http://127.0.0.1:8000"
email_delivery_service: smtp
database:
  host: "172.18.0.3"
  port: 5432
redis:
  host: "172.18.0.4"
  port: 6379
  db_number: 0
email_client:
  base_url: "http://172.18.0.7:8001"
  sender_email: "anymail@anydomain.com"
  timeout: 10000
object_storage:
  endpoint_url: "http://172.18.0.2:3900"
  region: "garage"
  bucket_name: "mustore-data"
recaptcha:
  endpoint_url: "http://ghashytest.com"
payments:
  merchant_api_endpoint: "http://localhost:15100"

