app_port: 8000
app_addr: "therewillbeappadr"
app_base_url: "therewillbeappbaseurl"
email_delivery_service: smtp
database:
  host: "postgres"
  port: 5432
redis:
  host: "redis"
  port: 6379
  db_number: 0
email_client:
  base_url: "https://api.smtp.bz"
  sender_email: "therewillbesenderemail"
  timeout: 10000
object_storage:
  endpoint_url: "https://storage.yandexcloud.net"
  region: "us-west-1"
  bucket_name: "mustore-data"


