Enum "UserRole" {
  "creator"
  "consumer"
  "fullstack"
}

Enum "MusicKey" {
  "a-minor"
  "a-major"
  "b-flat-minor"
  "b-flat-major"
  "b-minor"
  "b-major"
  "c-minor"
  "c-major"
  "c-sharp-minor"
  "c-sharp-major"
  "d-minor"
  "d-major"
  "e-flat-minor"
  "e-flat-major"
  "e-minor"
  "e-major"
  "f-minor"
  "f-major"
  "f-sharp-minor"
  "f-sharp-major"
  "g-minor"
  "g-major"
  "a-flat-minor"
  "a-flat-major"
}

Enum "ProductStatus" {
  "moderation"
  "denied"
  "active"
  "hidden"
  "sold"
}

Enum "ServiceStatus" {
  "moderation"
  "denied"
  "active"
  "hidden"
}

Enum "OfferStatus" {
  "pending"
  "accepted"
}

Enum "ServiceOrderStatus" {
  "paid"
  "delivered"
  "on_revision"
  "dispute"
  "rejected"
  "fulfiled"
}

Enum "ProductOrderStatus" {
  "created"
  "paid"
}

Enum "ObectType" {
  "image"
  "audio"
  "multitrack"
  "video"
  "attachment"
}

Table genres {
  id SERIAL [pk, increment]
  created_at TIMESTAMP [not null, default: `CURRENT_TIMESTAMP`]
  name VARCHAR(50) [not null]
}

Ref:genres.id < songs.primary_genre [delete: restrict]
Ref:genres.id < songs.secondary_genre [delete: restrict]
Ref:genres.id < beats.primary_genre [delete: restrict]
Ref:genres.id < beats.secondary_genre [delete: restrict]
Ref:genres.id < music_services_genres.genres_id [delete: restrict]

Table tags {
  id SERIAL [pk, increment]
  created_at TIMESTAMP [not null, default: `CURRENT_TIMESTAMP`]
  name VARCHAR(50) [not null]
}

Ref:tags.id < products_tags.tags_id [delete: restrict]

Table superusers {
  id SERIAL [pk, increment]
  created_at TIMESTAMP [not null, default: `CURRENT_TIMESTAMP`]
  updated_at TIMESTAMP [default: `CURRENT_TIMESTAMP`]
}

Ref:superusers.id < messages.superusers_id [delete: set null]
Ref:superusers.id < participants.superusers_id [delete: cascade]

Table admin_signup_tokens {
    id SERIAL [pk, increment]
    token VARCHAR(255) [not null]
    created_at TIMESTAMP [not null, default: `CURRENT_TIMESTAMP`]
    used BOOLEAN [not null, default: `FALSE`]
    administrators_id INTEGER
}

Table administrators {
  id SERIAL [pk, increment]
  created_at TIMESTAMP [not null, default: `CURRENT_TIMESTAMP`]
  updated_at TIMESTAMP [default: `CURRENT_TIMESTAMP`]
  name VARCHAR(50) [not null]
  password_hash VARCHAR(500) [not null]
}

Ref:administrators.id < messages.administrators_id [delete: set null]
Ref:administrators.id < participants.administrators_id [delete: cascade]
Ref:administrators.id < admin_signup_tokens.administrators_id [delete: set null]
Ref:administrators.id < strikes.administrators_id [delete: set null]
Ref:administrators.id < bans.administrators_id [delete: set null]

Table user_settings {
  id SERIAL [pk, increment]
  created_at TIMESTAMP [not null, default: `CURRENT_TIMESTAMP`]
  updated_at TIMESTAMP [default: `CURRENT_TIMESTAMP`]
  inbox_messages BOOL [not null, default: true]
  order_messages BOOL [not null, default: true]
  order_updates BOOL [not null, default: true]
}

Ref: user_settings.id < users.user_settings_id [delete: restrict]

Table users {
  id SERIAL [pk, increment]
  created_at TIMESTAMP [not null, default: `CURRENT_TIMESTAMP`]
  updated_at TIMESTAMP [default: `CURRENT_TIMESTAMP`]
  user_settings_id INTEGER [not null]
  username VARCHAR(50) [not null, unique]
  bio VARCHAR(400)
  email VARCHAR(100) [not null, unique]
  password_hash VARCHAR(500) [not null]
  status VARCHAR(50)
  role UserRole [not null]
  ban BOOL [not null, default: `FALSE`]
}

Ref:users.id < products.owner_id [delete: cascade]
Ref:users.id < consumer_reviews.consumer_id [delete: cascade]
Ref:users.id < likes.users_id [delete: cascade]
Ref:users.id < listenings.users_id [delete: cascade]
Ref:users.id < services.creator_id [delete: cascade]
Ref:users.id < views.users_id [delete: cascade]
Ref:users.id < favorites.users_id [delete: cascade]
Ref:users.id < product_orders.consumers_id [delete: set null]
Ref:users.id < service_orders.consumers_id [delete: set null]
Ref:users.id < transactions.users_id [delete: set null]
Ref:users.id < service_reviews.author_id [delete: set null]
Ref:users.id < messages.users_id [delete: set null]
Ref:users.id < participants.users_id [delete: cascade]
Ref:users.id < reports.users_id [delete: cascade]
Ref:users.id < system_notifications.users_id [delete: cascade]
Ref:users.id < support_tickets.users_id [delete: cascade]
Ref:users.id < objects.avatar_users_id [delete: restrict]
Ref:users.id < strikes.users_id [delete: cascade]
Ref:users.id < bans.users_id [delete: cascade]

Table objects {
  id SERIAL [pk, increment]
  created_at TIMESTAMP [not null, default: `CURRENT_TIMESTAMP`]
  updated_at TIMESTAMP [default: `CURRENT_TIMESTAMP`]
  key VARCHAR(500) [not null, unique]
  object_type "ObectType" [not null]
  avatar_users_id INTEGER [unique]
  cover_products_id INTEGER [unique]
  master_songs_id INTEGER [unique]
  multitrack_songs_id INTEGER [unique]
  master_beats_id INTEGER [unique]
  multitrack_beats_id INTEGER [unique]
  cover_services_id INTEGER [unique]
  video_description_services_id INTEGER [unique]
  mixing_credits_mixing_id INTEGER 
  song_credits_songs_id INTEGER
  beat_credits_beat_writing_id INTEGER
  cover_credits_cover_design_id INTEGER
  message_attachment INTEGER
}

Table products {
  id SERIAL [pk, increment]
  created_at TIMESTAMP [not null, default: `CURRENT_TIMESTAMP`]
  updated_at TIMESTAMP [default: `CURRENT_TIMESTAMP`]
  owner_id INTEGER [not null]
  name VARCHAR(30) [not null]
  description VARCHAR(400)
  price NUMERIC(10,2) [not null]
  status ProductStatus [not null]
}

Ref:products.id < products_tags.products_id [delete: cascade]
Ref:products.id < songs.products_id [delete: cascade]
Ref:products.id < beats.products_id [delete: cascade]
Ref:products.id < lyrics.products_id [delete: cascade]
Ref:products.id < covers.products_id [delete: cascade]
Ref:products.id < product_orders.products_id [delete: set null]
Ref:products.id < reports.products_id [delete: cascade]
Ref:products.id < objects.cover_products_id [delete: restrict]

Table products_tags {
  products_id INTEGER [not null]
  tags_id INTEGER [not null]
  Indexes {
    (products_id, tags_id) [pk, name: "pk_products_id"]
  }
}

Table songs {
  id SERIAL [pk, increment]
  products_id INTEGER [not null]
  primary_genre INTEGER [not null]
  secondary_genre INTEGER
  sex CHAR (1) [not null]
  tempo SMALLINT [not null]
  key MusicKey [not null]
  duration REAL [not null]
  lyric VARCHAR(1000) [not null]
}

Ref:songs.id < likes.songs_id [delete: cascade]
Ref:songs.id < listenings.songs_id [delete: cascade]
Ref:songs.id < views.songs_id [delete: cascade]
Ref:songs.id < objects.master_songs_id [delete: cascade]
Ref:songs.id < objects.multitrack_songs_id [delete: cascade]

Table beats {
  id SERIAL [pk, increment]
  products_id INTEGER [not null]
  primary_genre INTEGER [not null]
  secondary_genre INTEGER
  tempo SMALLINT [not null]
  key MusicKey [not null]
  duration REAL [not null]
}

Ref:beats.id < likes.beats_id [delete: cascade]
Ref:beats.id < listenings.beats_id [delete: cascade]
Ref:beats.id < views.beats_id [delete: cascade]
Ref:beats.id < objects.master_beats_id [delete: restrict]
Ref:beats.id < objects.multitrack_beats_id [delete: restrict]

Table lyrics {
  id SERIAL [pk, increment]
  products_id INTEGER [not null]
  text VARCHAR(5000) [not null]
}

Ref:lyrics.id < likes.lyrics_id [delete: cascade]
Ref:lyrics.id < views.lyrics_id [delete: cascade]

Table covers {
  id SERIAL [pk, increment]
  products_id INTEGER [not null]
}

Ref:covers.id < likes.covers_id [delete: cascade]
Ref:covers.id < views.covers_id [delete: cascade]

Table likes {
  created_at TIMESTAMP [not null, default: `CURRENT_TIMESTAMP`]
  users_id INTEGER [not null]
  songs_id INTEGER
  beats_id INTEGER
  lyrics_id INTEGER
  covers_id INTEGER
  Indexes {
  (users_id, songs_id, beats_id, lyrics_id, covers_id) [pk, name: "pk_likes"]
  }
}

Table listenings {
  created_at TIMESTAMP [not null, default: `CURRENT_TIMESTAMP`]
  users_id INTEGER [not null]
  songs_id INTEGER
  beats_id INTEGER
  Indexes {
    (users_id, songs_id, beats_id) [pk, name: "pk_listenings"]
  }
}

Table services {
  id SERIAL [pk, increment]
  created_at TIMESTAMP [not null, default: `CURRENT_TIMESTAMP`]
  updated_at TIMESTAMP [default: `CURRENT_TIMESTAMP`]
  creator_id INTEGER [not null]
  name VARCHAR(30) [not null]
  description VARCHAR(400)
  display_price NUMERIC(10,2) [not null]
  status ServiceStatus [not null, default: "active"]
}

Ref:services.id < mixing.services_id [delete: cascade]
Ref:services.id < service_orders.services_id [delete: set null]
Ref:services.id < song_writing.services_id [delete: cascade]
Ref:services.id < beat_writing.services_id [delete: cascade]
Ref:services.id < ghost_writing.services_id [delete: cascade]
Ref:services.id < cover_design.services_id [delete: cascade]
Ref:services.id < views.services_id [delete: cascade]
Ref:services.id < favorites.services_id [delete: cascade]
Ref:services.id < reports.services_id [delete: cascade]
Ref:services.id < objects.cover_services_id [delete: restrict]
Ref:services.id < objects.video_description_services_id [delete: restrict]
Ref:services.id < offers.services_id [delete: cascade]

Table mixing {
  id SERIAL [pk, increment]
  services_id INTEGER [not null]
}

Ref:mixing.id < music_services_genres.mixing_id [delete: cascade]
Ref:mixing.id < objects.mixing_credits_mixing_id [delete: restrict]

Table song_writing {
  id SERIAL [pk, increment]
  services_id INTEGER [not null]
}

Ref:song_writing.id < music_services_genres.song_writing_id [delete: cascade]
Ref:song_writing.id < objects.song_credits_songs_id [delete: restrict]

Table beat_writing {
  id SERIAL [pk, increment]
  services_id INTEGER [not null]
}

Ref:beat_writing.id < music_services_genres.beat_writing_id [delete: cascade]
Ref:beat_writing.id < objects.beat_credits_beat_writing_id [delete: restrict]

Table ghost_writing {
  id SERIAL [pk, increment]
  services_id INTEGER [not null]
}

Table cover_design {
  id SERIAL [pk, increment]
  services_id INTEGER [not null]
}

Ref:cover_design.id < objects.cover_credits_cover_design_id [delete: restrict]

Table music_services_genres {
  id SERIAL [pk, increment]
  created_at TIMESTAMP [not null, default: `CURRENT_TIMESTAMP`]
  genres_id INTEGER [not null]
  beat_writing_id INTEGER
  song_writing_id INTEGER
  mixing_id INTEGER
}

Table favorites {
  created_at TIMESTAMP [not null, default: `CURRENT_TIMESTAMP`]
  users_id INTEGER [not null]
  services_id INTEGER
  Indexes {
    (users_id, services_id) [pk, name: "pk_favorites"]
  }
}

Table product_orders {
  id SERIAL [pk, increment]
  created_at TIMESTAMP [not null, default: `CURRENT_TIMESTAMP`]
  updated_at TIMESTAMP [default: `CURRENT_TIMESTAMP`]
  consumers_id INTEGER
  products_id INTEGER
  name VARCHAR(30) [not null]
  price NUMERIC(10, 2) [not null]
  status ProductOrderStatus [not null, default: "created"]
}

Ref:product_orders.id < transactions.product_orders_id [delete: restrict]

Table service_orders {
  id SERIAL [pk, increment]
  created_at TIMESTAMP [not null, default: `CURRENT_TIMESTAMP`]
  updated_at TIMESTAMP [default: `CURRENT_TIMESTAMP`]
  consumers_id INTEGER
  services_id INTEGER
  conversations_id INTEGER [not null]
  delivery_date TIMESTAMP [not null]
  revisions INTEGER [not null]
  revision_price NUMERIC(10, 2) [not null]
  name VARCHAR(30) [not null]
  price NUMERIC(10, 2) [not null]
  status OrderStatus [not null, default: "paid"]
  delivered_on_time BOOL
}

Ref:service_orders.id < messages.service_orders_id [delete: cascade]
Ref:service_orders.id < participants.service_orders_id [delete: cascade]
Ref:service_orders.id < transactions.service_orders_id [delete: restrict]
Ref:service_orders.id < service_reviews.service_orders_id [delete: cascade]
Ref:service_orders.id < consumer_reviews.service_orders_id [delete: restrict]


// Ref:product_orders.id < transactions.orders_id [delete: restrict]

Table transactions {
  id SERIAL [pk, increment]
  created_at TIMESTAMP [not null, default: `CURRENT_TIMESTAMP`]
  users_id INTEGER
  product_orders_id INTEGER
  service_orders_id INTEGER
  description VARCHAR(200) [not null]
  from_desc VARCHAR(200) [not null]
  for_desc VARCHAR(200) [not null]
  money_amount NUMERIC(10,2) [not null]
}

Table service_reviews {
  id SERIAL [pk, increment]
  created_at TIMESTAMP [not null, default: `CURRENT_TIMESTAMP`]
  updated_at TIMESTAMP [default: `CURRENT_TIMESTAMP`]
  author_id INTEGER
  service_orders_id INTEGER [not null]
  text VARCHAR(400) [not null]
  mark SMALLINT [not null]
}

Table consumer_reviews {
  id SERIAL [pk, increment]
  created_at TIMESTAMP [not null, default: `CURRENT_TIMESTAMP`]
  updated_at TIMESTAMP [default: `CURRENT_TIMESTAMP`]
  author_id INTEGER
  consumer_id INTEGER
  service_orders_id INTEGER [not null]
  text VARCHAR(400) [not null]
  mark SMALLINT [not null]
}

Table conversations {
  id SERIAL [pk, increment]
  created_at TIMESTAMP [not null, default: `CURRENT_TIMESTAMP`]
  updated_at TIMESTAMP [default: `CURRENT_TIMESTAMP`]
}

Ref:conversations.id < messages.conversations_id [delete: cascade]
Ref:conversations.id < participants.conversations_id [delete: cascade]
Ref:conversations.id < service_orders.conversations_id [delete: cascade]
Ref:conversations.id < offers.conversations_id [delete: cascade]

Table messages {
  id SERIAL [pk, increment]
  created_at TIMESTAMP [not null, default: `CURRENT_TIMESTAMP`]
  updated_at TIMESTAMP [default: `CURRENT_TIMESTAMP`]
  conversations_id INTEGER [not null]
  service_orders_id INTEGER
  users_id INTEGER
  administrators_id INTEGER
  superusers_id INTEGER
  messages_id INTEGER
  text VARCHAR(2500) [not null]
}

Ref:messages.id < views.messages_id [delete: cascade]
Ref:messages.id < reports.messages_id [delete: cascade]
Ref:messages.id < objects.message_attachment [delete: restrict]

Table participants {
  id SERIAL [pk, increment]
  created_at TIMESTAMP [not null, default: `CURRENT_TIMESTAMP`]
  conversations_id INTEGER
  service_orders_id INTEGER
  users_id INTEGER
  administrators_id INTEGER
  superusers_id INTEGER
}

Table offers {
  id SERIAL [pk, increment]
  created_at TIMESTAMP [not null, default: `CURRENT_TIMESTAMP`]
  conversations_id INTEGER [not null]
  services_id INTEGER [not null]
  price NUMERIC(10,2) [not null]
  delivery_date TIMESTAMP [not null]
  free_revisions INTEGER [not null]
  revision_price NUMERIC(10,2) [not null]
  status OfferStatus [not null]
}

Table system_notifications {
  id SERIAL [pk, increment]
  created_at TIMESTAMP [not null, default: `CURRENT_TIMESTAMP`]
  users_id INTEGER [not null]
  text VARCHAR(2500) [not null]
}

Ref: system_notifications.id < views.system_notifications_id [delete: cascade]


Table views {
  created_at TIMESTAMP [not null, default: `CURRENT_TIMESTAMP`]
  users_id INTEGER [not null]
  services_id INTEGER
  songs_id INTEGER
  beats_id INTEGER
  lyrics_id INTEGER
  covers_id INTEGER
  messages_id INTEGER
  system_notifications_id INTEGER
  Indexes {
    (users_id, songs_id, beats_id, lyrics_id, covers_id, messages_id) [pk, name: "pk_views"]
  }
}

Table reports {
  id SERIAL [pk, increment]
  created_at TIMESTAMP [not null, default: `CURRENT_TIMESTAMP`]
  updated_at TIMESTAMP [default: `CURRENT_TIMESTAMP`]
  users_id INTEGER [not null]
  messages_id INTEGER
  services_id INTEGER
  products_id INTEGER
  is_open BOOL [not null, default: true]
}

Table support_tickets {
  id SERIAL [pk, increment]
  created_at TIMESTAMP [not null, default: `CURRENT_TIMESTAMP`]
  updated_at TIMESTAMP [default: `CURRENT_TIMESTAMP`]
  users_id INTEGER [not null]
  text VARCHAR(2500) [not null]
  is_open BOOL [not null, default: true]
  attachments "VARCHAR(1000)[]" 
}

Table strikes {
  id SERIAL [pk, increment]
  created_at TIMESTAMP [not null, default: `CURRENT_TIMESTAMP`]
  updated_at TIMESTAMP [default: `CURRENT_TIMESTAMP`]
  users_id INTEGER [not null]
  administrators_id INTEGER 
  comment VARCHAR(1000) [not null]
}

Table bans {
  id SERIAL [pk, increment]
  created_at TIMESTAMP [not null, default: `CURRENT_TIMESTAMP`]
  duration INTERVAL [not null]
  users_id INTEGER [not null]
  administrators_id INTEGER 
  comment VARCHAR(1000) [not null]
}

Ref: "product_orders"."status" < "consumer_reviews"."id"
