#!/usr/bin/env bash

docker run --rm -v "${PWD}/doc/mustore-pg-schema:/output" -v "${PWD}/secrets/schemaspy.properties:/schemaspy.properties"  schemaspy/schemaspy:latest -configFile /schemaspy.properties  -noimplied -nopages -l
