import { CarouselItemProps } from "../../../../types/types";
import cover_1 from "../../../../assets/HomePage/album_covers/ablum_cover_1.png";
import cover_2 from "../../../../assets/HomePage/album_covers/ablum_cover_2.png";
import cover_3 from "../../../../assets/HomePage/album_covers/ablum_cover_3.png";
import cover_4 from "../../../../assets/HomePage/album_covers/ablum_cover_4.png";
import cover_5 from "../../../../assets/HomePage/album_covers/ablum_cover_5.png";
import cover_6 from "../../../../assets/HomePage/album_covers/ablum_cover_6.png";
import cover_7 from "../../../../assets/HomePage/album_covers/ablum_cover_7.png";
import cover_8 from "../../../../assets/HomePage/album_covers/ablum_cover_8.png";

export const carousel_items_rec: CarouselItemProps[] = [
  {
    id: 1,
    cover_url: cover_1,
    name: "Будь рядом",
    author: "ALENA NAI",
    price: 100_000,
    likes: 49,
    type: "recommended",
  },
  {
    id: 2,
    cover_url: cover_2,
    name: "Закат",
    author: "KartenMusic",
    price: 70_000,
    likes: 35,
    type: "recommended",
  },
  {
    id: 3,
    cover_url: cover_3,
    name: "Ночные часы",
    author: "Camely",
    price: 90_000,
    likes: 32,
    type: "recommended",
  },
  {
    id: 4,
    cover_url: cover_4,
    name: "Забуду тебя",
    author: "Atires",
    price: 60_000,
    likes: 29,
    type: "recommended",
  },
  {
    id: 5,
    cover_url: cover_5,
    name: "В окне",
    author: "SIBERD",
    price: 30_000,
    likes: 13,
    type: "recommended",
  },
  {
    id: 6,
    cover_url: cover_6,
    name: "Вечером одна",
    author: "Ababbul",
    price: 56_000,
    likes: 21,
    type: "recommended",
  },
  {
    id: 7,
    cover_url: cover_7,
    name: "Будь рядом",
    author: "ALENA NAI",
    price: 100_000,
    likes: 49,
    type: "recommended",
  },
  {
    id: 8,
    cover_url: cover_8,
    name: "Закат",
    author: "KartenMusic",
    price: 70_000,
    likes: 35,
    type: "recommended",
  },
  {
    id: 9,
    cover_url: cover_3,
    name: "Ночные часы",
    author: "Camely",
    price: 90_000,
    likes: 32,
    type: "recommended",
  },
  {
    id: 10,
    cover_url: cover_4,
    name: "Забуду тебя",
    author: "Atires",
    price: 60_000,
    likes: 29,
    type: "recommended",
  },
  {
    id: 11,
    cover_url: cover_5,
    name: "В окне",
    author: "SIBERD",
    price: 30_000,
    likes: 13,
    type: "recommended",
  },
  {
    id: 12,
    cover_url: cover_6,
    name: "Вечером одна",
    author: "Ababbul",
    price: 56_000,
    likes: 21,
    type: "recommended",
  },
  {
    id: 13,
    cover_url: cover_1,
    name: "Вечером одна",
    author: "Ababbul",
    price: 56_000,
    likes: 21,
    type: "recommended",
  },
  {
    id: 14,
    cover_url: cover_7,
    name: "Будь рядом",
    author: "ALENA NAI",
    price: 100_000,
    likes: 49,
    type: "recommended",
  },
  {
    id: 15,
    cover_url: cover_8,
    name: "Закат",
    author: "KartenMusic",
    price: 70_000,
    likes: 35,
    type: "recommended",
  },
];
